services:
    cyberspectrum.pdflatex.executor_factory:
        class: CyberSpectrum\PdfLatexBundle\PdfLatex\ExecutorFactory
        arguments:
            - "%cyberspectrum.pdflatex.binary%"
        public: false

    cyberspectrum.pdflatex.processor:
        class: CyberSpectrum\PdfLatexBundle\PdfLatex\JobProcessor
        arguments:
            - "@cyberspectrum.pdflatex.executor_factory"
            - "%kernel.cache_dir%/pdflatex"
        public: true

    cyberspectrum.pdflatex.twig.extension:
        class: CyberSpectrum\PdfLatexBundle\Twig\Extension
        tags:
            - { name: twig.extension }
        public: false

    cyberspectrum.pdflatex.twig.file_extension_escaping_strategy:
        class: CyberSpectrum\PdfLatexBundle\Twig\FileExtensionEscapingStrategy
        arguments:
            - false
        public: false
