services:
    CyberSpectrum\PdfLatexBundle\PdfLatex\ExecutorFactory:
        arguments:
            $latexBinary: null
        public: false

    CyberSpectrum\PdfLatexBundle\PdfLatex\JobProcessor:
        arguments:
            $executorFactory: '@CyberSpectrum\PdfLatexBundle\PdfLatex\ExecutorFactory'
            $tempDirectory: null
        public: true

    CyberSpectrum\PdfLatexBundle\Twig\Extension:
        tags:
            - { name: twig.extension }
        public: false

    CyberSpectrum\PdfLatexBundle\Twig\FileExtensionEscapingStrategy:
        arguments:
            $defaultStrategy: false
        public: false
