services:
    CyberSpectrum\PdfLatexBundle\PdfLatex\ExecutorFactory:
        arguments:
            - '%cyberspectrum.pdflatex.binary%'
        public: false

    CyberSpectrum\PdfLatexBundle\PdfLatex\JobProcessor:
        arguments:
            - '@CyberSpectrum\PdfLatexBundle\PdfLatex\ExecutorFactory'
            - '%kernel.cache_dir%/pdflatex'
        public: true

    CyberSpectrum\PdfLatexBundle\Twig\Extension:
        tags:
            - { name: twig.extension }
        public: false

    CyberSpectrum\PdfLatexBundle\Twig\FileExtensionEscapingStrategy:
        arguments:
            - false
        public: false
